import { InferableComponentEnhancerWithProps } from 'react-redux';
export declare const init: (playLists?: Recording.IPlayList[]) => Promise<any>;
export declare const middleware: Redux.Middleware;
export declare const saga: () => IterableIterator<any>;
export declare const globalReducer: App.IReducer<IState>;
export declare const reducer: App.IReducer<Recording.IState>;
export declare const providerConnector: InferableComponentEnhancerWithProps<Recording.IStateProps & Recording.IDispatchProps, {}>;
export declare const blockGuiSaga: () => IterableIterator<any>;
export declare const blockGuiReducer: App.IReducer<BlockGui.IState>;
export declare const blockGuiConnector: InferableComponentEnhancerWithProps<BlockGui.IState, {}>;
